version: '3'
services:
  bridger-kc:
    container_name: bridger-kc
    image: bitnami/keycloak
    # ports:
    #   - 8003:8080
    restart: unless-stopped
    environment:
      - KEYCLOAK_ADMIN_USER=${KEYCLOAK_ADMIN_USER}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - KEYCLOAK_DATABASE_HOST=bridger-kc-db
      - KEYCLOAK_DATABASE_NAME=keycloak
      - KEYCLOAK_DATABASE_USER=keycloak
      - KEYCLOAK_DATABASE_PASSWORD=asdfoinvsdoignas

  bridger-kc-db:
    image: postgres
    container_name: bridger-kc-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=asdfoinvsdoignas
      - POSTGRES_DB=keycloak
    volumes:
      - /home/bridger/data/kcpostgres:/var/lib/postgresql/data

  bridger-kc-swag:
    image: lscr.io/linuxserver/swag
    container_name: bridger-kc-swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
      - URL=bridgerkc.duckdns.org
      - VALIDATION=duckdns
      - DUCKDNSTOKEN=${DUCKDNSTOKEN}
      - STAGING=false
    volumes:
      - /home/bridger/data/kcswag:/config
      - ./swag-default.conf:/config/nginx/site-confs/default.conf
    ports:
      - 0.0.0.0:8003:443
    restart: unless-stopped
