version: '3'
services:
  bridger-kc:
    container_name: bridger-kc
    image: bitnami/keycloak
    ports:
      - 8003:8080
    restart: unless-stopped
    environment:
      - KEYCLOAK_ADMIN_USER=admin
      - KEYCLOAK_ADMIN_PASSWORD=password
      - KEYCLOAK_DATABASE_HOST=bridger-kc-db
      - KEYCLOAK_DATABASE_NAME=keycloak
      - KEYCLOAK_DATABASE_USER=keycloak
      - KEYCLOAK_DATABASE_PASSWORD=asdfoinvsdoignas

  bridger-kc-db:
    image: postgres
    container_name: bridger-kc-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=asdfoinvsdoignas
      - POSTGRES_DB=keycloak
    volumes:
      - /tmp/postgres:/var/lib/postgresql/data
